name: Publish package to GitHub Packages
on:
  workflow_dispatch: {}
  push:
    branches:
      - 'KT-*'
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
      - run: echo $(mvn help:evaluate -Dexpression="project.version" -q -DforceStdout| sed -i 's/SNAPSHOT/${{ github.ref##*/ }}-SNAPSHOT:g')
      - name: Set projects Maven version to GitHub Action GUI set version
        run: mvn versions:set "-DnewVersion=${{ github.event.inputs.releaseversion }}"
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
